initialization
user: aUser
	usernameField textHolder value: aUser username.
	lastNameField textHolder value: aUser lastName.
	firstNameField textHolder value: aUser firstName.
	passwordField textHolder value: aUser password.
	addressField textHolder value: aUser address.
	emailField textHolder value: aUser email.
	phoneNumberField textHolder value: aUser phoneNumber.
	companyField textHolder value: aUser company.
	roleField textHolder value: aUser roleInCompany.
	user := aUser.
	