hooks
style
	"CSS"

	^ '
		.content {
    		margin: auto;
			text-align: center;
			width: 100%;
		}
		
		#componentTab {
			margin: auto;
			float: center;
		}
		
		.leftComponent { 
			text-align: right;
		}
		
		.rightComponent { 
			text-align: left;
		}
		
		.leftForm { 
			float: left;
			width: 47%;
			text-align: right;
		}

		.rightForm { 
			float: left;
			width: 20%;
			text-align: center;
		}
	'