initialization
firstName: aFirstNameString lastName: aLastNameString email: anEmailString phoneNumber: aPhoneNumberString address: anAddressString company: aCompanyString position: aPositionString
	^ self new
		firstName: aFirstNameString;
		lastName: aLastNameString;
		email: anEmailString;
		phoneNumber: aPhoneNumberString;
		address: anAddressString;
		company: aCompanyString;
		position: aPositionString;
		yourself