initialization
generateAttributes

	attributes 
			addValue: 7 + ( 5 atRandom ) at: AttributeTypeEnum agility;
			addValue: 7 + ( 5 atRandom ) at: AttributeTypeEnum dexterity;
			addValue: 7 + ( 5 atRandom ) at: AttributeTypeEnum intelligence;
			addValue: 7 + ( 5 atRandom ) at: AttributeTypeEnum luck;
			addValue: 7 + ( 5 atRandom ) at: AttributeTypeEnum strenght;
			addValue: 7 + ( 5 atRandom ) at: AttributeTypeEnum vitality.
					 