tests
testChieftan
self assert: (UnitTypeChieftan unitName) equals: 'Chieftan'.
self assert: (UnitTypeChieftan maxHp ) equals: 50.
self assert: (UnitTypeChieftan maxXp ) equals: 50.
self assert: (UnitTypeChieftan attack ) equals: 15. "nutno doimplementovat"
self assert: (UnitTypeChieftan move ) equals: 2.
self assert: (UnitTypeChieftan lvl ) equals: 3.
self assert: (UnitTypeChieftan upgrades ) equals: nil  .

     
