drawing
drawFlag: aCanvas
		aCanvas stroke
			paint: (Color red);
			path: (aCanvas shape 
				line: 10@10 to: 10@4 );
			width: 2; 
			draw.
	
	aCanvas stroke
			paint: (Color black);
			path: (aCanvas shape 
				line: 10@16 to: 10@10 );
			width: 2; 
			draw.
	
	aCanvas stroke
			paint: (Color red);
			path: (aCanvas shape 
				line: 10@4 to: 5@7  );
			width: 2; 
			draw.
	
	aCanvas stroke
			paint: (Color red);
			path: (aCanvas shape 
				line: 10@10 to: 5@7  );
			width: 2; 
			draw.
			
	aCanvas stroke
			paint: (Color red);
			path: (aCanvas shape 
				line: 10@8 to: 7@5  );
			width: 2; 
			draw.
			
		aCanvas stroke
			paint: (Color black);
			path: (aCanvas shape 
				line: 4@16 to: 16@16 );
			width: 2; 
			draw.
			
		aCanvas stroke
			paint: (Color black);
			path: (aCanvas shape 
				line: 7@14 to: 13@14 );
			width: 2; 
			draw.