SystemOrganization addCategory: #ContactManager!
SystemOrganization addCategory: 'ContactManager-Entities'!
SystemOrganization addCategory: 'ContactManager-Navigation'!
SystemOrganization addCategory: 'ContactManager-Services'!
SystemOrganization addCategory: 'ContactManager-Tests'!
SystemOrganization addCategory: 'ContactManager-Utilities'!
SystemOrganization addCategory: 'ContactManager-Validation'!
SystemOrganization addCategory: 'ContactManager-WAComponent'!
